name: cleaneasyalert
description: With EasyAlert, instantly display animated alert dialogs such as success, error, warning, confirm, loading or even a custom dialog.
version: 1.0.1
homepage: https://easyalert.laxmanmagarati.com.np

environment:
  sdk: ">=2.17.6 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  